version: '3.8'

services:
  app:
    build:
      context: .
    stop_signal: SIGKILL
    ports:
      - "8080:8080"
      - "9998:9998"
    volumes:
      - $PWD:/dev/go-remote-debug
    working_dir: /dev/go-remote-debug
    environment:
      DEBUG_PORT: 9998
